server:
  port: 8081
  
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8070/eureka
      instance:
      preferIpAddress: false 

spring: 
    datasource:
        username: postgres
        password: postgres
        url: jdbc:postgresql://localhost:5432/ostock_dev
    jpa:
        generate-ddl: true
    cloud:
          stream:
            bindings:
               output:
                 destination: orgChangeTopic
                 content-type: application/json
            kafka:
               binder:
                 zkNodes: localhost
                 brokers: localhost

keycloak:
    realm: spmia-realm
    auth-server-url: http://localhost:8080
    ssl-required: external
    resource: ostock
    credentials:
      secret: NN8Nj6kKsimwMdhbJBx22tRureZEk5Y6
    use-resource-role-mappings: true
    bearer-only: true


