spring:
  application:
    name: config-server
  profiles:
    active:
    - native, git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/fabiop35/configSMIA.git
          #searchPaths: licensingservice

server:
  port: 8071
  
