spring:
  application:
    name: config-server
  profiles:
    active:
    - vault
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/fabiop35/configSMIA.git
          #searchPaths: licensingservice
        vault:
          port: 8200
          host: 127.0.0.1
          knVersion: 2

server:
  port: 8071
  
